// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Header$ReactHooksTemplate = require("./Header.bs.js");
var Search$ReactHooksTemplate = require("./Search.bs.js");

function App(Props) {
  var match = React.useReducer((function (state, action) {
          if (action.tag) {
            var payload = action[0];
            return List.filter((function (poke) {
                            return poke !== payload;
                          }))(state);
          } else {
            return /* :: */[
                    action[0],
                    state
                  ];
          }
        }), /* [] */0);
  var dispatch = match[1];
  var pokemons = match[0];
  var addPoke = function (poke) {
    return Curry._1(dispatch, /* AddPoke */Block.__(0, [poke]));
  };
  return React.createElement("div", undefined, React.createElement(Header$ReactHooksTemplate.make, {
                  children: "Header!"
                }), React.createElement(Search$ReactHooksTemplate.make, {
                  addPoke: addPoke,
                  isAddDisabled: List.length(pokemons) >= 6
                }), $$Array.of_list(List.map((function (poke) {
                        return React.createElement("div", undefined, poke, React.createElement("button", {
                                        onClick: (function (_event) {
                                            return Curry._1(dispatch, /* RemovePoke */Block.__(1, [poke]));
                                          })
                                      }, "Remove"));
                      }), pokemons)));
}

var make = App;

exports.make = make;
/* react Not a pure module */
