// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Header(Props) {
  var children = Props.children;
  return React.createElement("h1", undefined, children);
}

var make = Header;

exports.make = make;
/* react Not a pure module */
