// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Search(Props) {
  var addPoke = Props.addPoke;
  var isAddDisabled = Props.isAddDisabled;
  var match = React.useReducer((function (_state, action) {
          if (action) {
            return action[0];
          } else {
            return "";
          }
        }), "");
  var dispatch = match[1];
  var value = match[0];
  return React.createElement("div", undefined, React.createElement("input", {
                  placeholder: "Placeholder...",
                  value: value,
                  onChange: (function ($$event) {
                      return Curry._1(dispatch, /* Change */[$$event.target.value]);
                    })
                }), React.createElement("button", {
                  disabled: isAddDisabled,
                  onClick: (function (_event) {
                      Curry._1(addPoke, value);
                      return Curry._1(dispatch, /* Clear */0);
                    })
                }, "Add"));
}

var make = Search;

exports.make = make;
/* react Not a pure module */
